VIDEO_EXTENSION = 'mkv'
VIDEO_CODEC = 'h264'
IMAGE_EXTENSIONS = ('.jpg', 'jpeg', 'png', 'tiff', 'bmp', 'webp')

PUBSUB_VIDEO_CHANNEL_NAME = "video"

DATE_FORMAT = '%Y-%m-%dT%H:%M:%S'
TIME_FORMAT = '%H-%M'

DATA_RANGE_INTERVAL_IN_MINUTES = 60

RECONNECT_DELAY_SECONDS = 10

REDIS_SERVER = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0

# Портится через год
# CLOUD_ACCESS_TOKEN = 'y0_AgAAAAA83hh6AAk_4QAAAADfgmJZgRgekPOASoSfsXFl8a3coiyew-U'  # Roby.market
CLOUD_ACCESS_TOKEN = 'y0_AgAAAAALeWngAAk_4QAAAADhNY13bDy5DG7RRCeiby8aDYpzelmB_wY'  # Planeta
